services:
  mongo:
    image: mongo:6
    container_name: mongo-rest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db

  user:
    build:
      context: .
      dockerfile: user/Dockerfile
    container_name: user-rest
    ports:
      - "${USER_PORT}:${USER_PORT}"
    volumes:
      - ./user/databases:/app/user/databases
    environment:
      - MONGO_URI=${MONGO_URI_DOCKER}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - USE_MONGO=${USE_MONGO}
  
  movie:
    build:
      context: .
      dockerfile: movie/Dockerfile
    container_name: movie-rest
    ports:
      - "${MOVIE_PORT}:${MOVIE_PORT}"
    volumes:
      - ./movie/databases:/app/movie/databases
    environment:
      - MONGO_URI=${MONGO_URI_DOCKER}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - USE_MONGO=${USE_MONGO}

  schedule:
    build:
      context: .
      dockerfile: schedule/Dockerfile
    container_name: schedule-rest
    ports:
      - "${SCHEDULE_PORT}:${SCHEDULE_PORT}"
    volumes:
      - ./schedule/databases:/app/schedule/databases
    environment:
      - MONGO_URI=${MONGO_URI_DOCKER}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - USE_MONGO=${USE_MONGO}
      - MOVIE_SERVICE_URL=${MOVIE_SERVICE_URL_DOCKER}

  booking:
    build:
      context: .
      dockerfile: booking/Dockerfile
    container_name: booking-rest
    ports:
      - "${BOOKING_PORT}:${BOOKING_PORT}"
    volumes:
      - ./booking/databases:/app/booking/databases
    environment:
      - MONGO_URI=${MONGO_URI_DOCKER}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - USE_MONGO=${USE_MONGO}
      - USER_SERVICE_URL=${USER_SERVICE_URL_DOCKER}
      - SCHEDULE_SERVICE_URL=${SCHEDULE_SERVICE_URL_DOCKER}
volumes:
  mongo_data: