services:
  mongo:
    image: mongo:6
    container_name: mongo-rest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user:
    build:
      context: .
      dockerfile: user/Dockerfile
    container_name: user-rest
    ports:
      - "3203:3203"
    volumes:
      - ./user/databases:/app/user/databases
    environment:
      - MONGO_URI=${MONGO_URI_DOCKER}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - USE_MONGO=${USE_MONGO}
  
  movie:
    build:
      context: .
      dockerfile: movie/Dockerfile
    container_name: movie-rest
    ports:
      - "3200:3200"
    volumes:
      - ./movie/databases:/app/movie/databases
    environment:
      - MONGO_URI=${MONGO_URI_DOCKER}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - USE_MONGO=${USE_MONGO}

  schedule:
    build:
      context: .
      dockerfile: schedule/Dockerfile
    container_name: schedule-rest
    ports:
      - "3202:3202"
    volumes:
      - ./schedule/databases:/app/schedule/databases
    environment:
      - MONGO_URI=${MONGO_URI_DOCKER}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - USE_MONGO=${USE_MONGO}
      - MOVIE_SERVICE_URL=${MOVIE_SERVICE_URL_DOCKER}
volumes:
  mongo_data: